# Generated by Django 4.1.7 on 2023-03-13 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя заказчика')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия заказчика')),
                ('email', models.EmailField(max_length=256, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('status', models.SmallIntegerField(choices=[(0, 'Создан заказ'), (1, 'Заказ оплачен'), (2, 'Заказ в пути'), (3, 'Заказ доставлен')], default=0)),
                ('basket_history', models.JSONField(default=dict)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
